entrega_final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('inicio/', include('inicio.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'

urlpatterns = [
    
    # path('carros/crear/', views.crear_carro, name='crear_carro'),
    # path('carros/', views.lista_carros, name='listar_carro'),
    # path('carros/eliminar/<int:id_carro>', views.eliminar_carro, name='eliminar_carro'),
    # path('carros/modificar/<int:id_carro>', views.eliminar_carro, name='modificar_carro'),
    
    path('', views.mi_inicio, name='inicio'),
    path('about/', views.about, name='about'),
    path('carros/', views.ListaCarros.as_view(), name='listar_carros'),
    path('carros/crear/', views.CrearCarro.as_view(), name='crear_carro'),
    path('carros/<int:pk>/', views.MostrarCarro.as_view(), name='mostrar_carro'),
    path('carros/<int:pk>/eliminar/', views.EliminarCarro.as_view(), name='eliminar_carro'),
    path('carros/<int:pk>/modificar/', views.ModificarCarro.as_view(), name='modificar_carro'),
]   

usuarios/urls.py
from django.urls import path
from usuarios import views
from django.contrib.auth.views import LogoutView

app_name = 'usuarios'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registro/', views.registro, name='registro'),
    path('editar-perfil/', views.editar_perfil, name='editar_perfil'),
    path('logout/', LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    path('cambio-contrasenia/', views.CambioContrasenia.as_view(), name='cambio_contrasenia'),
]

inicio/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.


class Carro(models.Model):
    modelo = models.CharField(max_length=80)
    marca = models.CharField(max_length=80)
    descripcion=RichTextField(blank=True)
    precio = models.IntegerField()
    anio_fabricacion = models.IntegerField()
    

    def __str__(self):
        return f'El carro de modelo "{self.modelo}" es de la marca "{self.marca}" tiene el precio de "{self.precio} dolares" y su fabricación es del año "{self.anio_fabricacion}"'
    

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class InformacionExtra(models.Model):
    avatar = models.ImageField(upload_to='avatares', null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=80, null=True, blank=True)

inicio/forms.py
from django import forms



class BaseCarroFormulario(forms.Form):
    modelo = forms.CharField(max_length=80)
    marca = forms.CharField(max_length=80)
    precio = forms.IntegerField()
    anio_fabricacion = forms.IntegerField()

class CreacionCarroFormulario(BaseCarroFormulario):
    ...
    
class ModificarCarroFormulario(BaseCarroFormulario):
    ...
    
    
    
class BuscarCarro(forms.Form):
    modelo = forms.CharField(max_length=80, required=False)
    
# class ModificarAnimalFormulario(forms.Form):
        

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

class MiFormularioDeCreacion(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label='Contrasenia', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repetir Contrasenia', widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {k: '' for k in fields}
        
class EdicionDatosUsuario(UserChangeForm):
    password = None
    email = forms.EmailField()
    first_name = forms.CharField(label='Nombre', max_length=20)
    last_name = forms.CharField(label='Apellido', max_length=20)
    descripcion = forms.CharField(label='Descripcion', max_length=200, required=False)
    avatar = forms.ImageField(required=False)
    
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'descripcion', 'avatar']
        

inicio/views.py
from inicio.models import Carro
from django.shortcuts import render

from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy


# Create your views here.

def mi_inicio(request):
    return render(request, 'inicio/inicio.html')

def about(request):
    print('PASE POR ACA!!!!!')
    return render(request, 'inicio/about.html')

class ListaCarros(ListView):
    model = Carro
    template_name = 'inicio\lista_carros.html'
    
class CrearCarro(CreateView):
    model = Carro
    template_name = 'inicio\crear_carro.html'
    success_url = reverse_lazy('inicio:listar_carros')
    fields = ['modelo', 'marca', 'precio', 'anio_fabricacion']  
  
class ModificarCarro(LoginRequiredMixin, UpdateView):
    model = Carro
    template_name = 'inicio\modificar_carro.html'
    success_url = reverse_lazy('inicio:listar_carros')
    fields = ['modelo', 'marca', 'precio', 'anio_fabricacion'] 
    
class EliminarCarro(LoginRequiredMixin, DeleteView):
    model = Carro
    template_name = 'inicio\eliminar_carro.html'
    success_url = reverse_lazy('inicio:listar_carros')
    
class MostrarCarro(DetailView):
    model = Carro
    template_name = 'inicio/mostrar_carro.html'

usuarios/views.py
from django.shortcuts import render
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import authenticate, login as django_login
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from usuarios.models import InformacionExtra

from usuarios.forms import MiFormularioDeCreacion, EdicionDatosUsuario

# Create your views here.

def login(request):
    
    if request.method == 'POST':
        formulario = AuthenticationForm(request, data=request.POST)
        
        if formulario.is_valid():
            nombre_usuario = formulario.cleaned_data.get('username')
            contrasenia = formulario.cleaned_data.get('password')
            usuario = authenticate(username=nombre_usuario, password=contrasenia)
            django_login(request, usuario)
            InformacionExtra.objects.get_or_create(user=request.user)
            return redirect('inicio:inicio')
        else:
            return render(request, 'usuarios/login.html', {'formulario': formulario})
            
    
    formulario = AuthenticationForm()
    return render(request, 'usuarios/login.html', {'formulario': formulario})

def registro(request):
    
    if request.method == "POST":
        formulario = MiFormularioDeCreacion(request.POST)
        
        if formulario.is_valid():
            formulario.save()
            return redirect('usuarios:login')
        else:
            return render(request, 'usuarios/registro.html', {'formulario': formulario})
            
    
    formulario = MiFormularioDeCreacion()
    return render(request, 'usuarios/registro.html', {'formulario': formulario})

@login_required
def editar_perfil(request):
    if request.method == "POST":
        formulario = EdicionDatosUsuario(request.POST, request.FILES, instance=request.user)
        
        if formulario.is_valid():
            if formulario.cleaned_data.get('avatar'):
                request.user.informacionextra.avatar = formulario.cleaned_data.get('avatar')
            request.user.informacionextra.save()
            formulario.save()
            return redirect('inicio:inicio')
        else:
            return render(request, 'usuarios/editar_perfil.html', {'formulario': formulario})
            
    formulario = EdicionDatosUsuario(initial={'avatar': request.user.informacionextra.avatar}, instance=request.user)
    return render(request, 'usuarios/editar_perfil.html', {'formulario': formulario})
    
    
class CambioContrasenia(PasswordChangeView):
    template_name = 'usuarios/cambiar_contrasenia.html'
    success_url = reverse_lazy('usuarios:editar_perfil')
    

inicio/templates/inicio/about.html
{% extends 'genericos/base.html' %}


{% block title_head %}
<title>About</title>
{% endblock title_head %}

{% block l1_nav %}
<li class="nav-item"><a class="nav-link" href="#contact">Contacto</a></li>
{% endblock l1_nav %}

{% block h1_header %}
<h1 class="mx-auto my-0 text-uppercase">SOBRE LA PÁGINA</h1>
<h2 class="text-white-50 mx-auto mt-2 mb-5">La página trata de registrar autmóviles, se ingresa el Modelo, la Marca, el Precio y el anio de fabricación.</h2>
{% endblock h1_header %}




{% block footer %}

{% endblock footer %}

inicio/templates/inicio/crear_carro.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Registro de Carros</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Registrar Carro</h1>
{% endblock h1_header %}


{% block contenido %}
<form style="color:white" action={% url 'inicio:crear_carro' %} method="POST">
    {% csrf_token %}
    <table>
        {{form.media}}   
        {{form}}        
    </table>
    <button>Crear</button>
</form>
{% endblock contenido %}


{% block about %}
{% endblock about %}

{% block contact%}
{% endblock contact%}

{% block footer %}
{% endblock footer %}

inicio/templates/inicio/eliminar_carro.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Eliminar Carro</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Eliminar Carro</h1>
{% endblock h1_header %}


{% block contenido %}

<form style="color:white" action={% url 'inicio:eliminar_carro' carro.id %} method="POST">
    {% csrf_token %}
    <p>Desea realmente eliminar el carro {{carro}}</p>
    <button>Eliminar</button>
</form>
{% endblock contenido %}


{% block about %}
{% endblock about %}

{% block contact%}
{% endblock contact%}

{% block footer %}
{% endblock footer %}

inicio/templates/inicio/inicio.html
{% extends 'genericos/base.html' %}


{% block title_head %}
<title>Página de Inicio</title>
{% endblock title_head %}

{% block l1_nav %}
<li class="nav-item"><a class="nav-link" href="#contact">Contacto</a></li>
{% endblock l1_nav %}

{% block h1_header %}
<h1 class="mx-auto my-0 text-uppercase">Bienvenidos</h1>
<h2 class="text-white-50 mx-auto mt-2 mb-5">A MI PÁGINA PRINCIPAL</h2>
{% endblock h1_header %}




{% block footer %}

{% endblock footer %}

inicio/templates/inicio/lista_carros.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Mostrar carros</title>
{% endblock title_head %}

{% block h1_header %}
<h1 class="mx-auto my-0 text-uppercase">LISTADO DE CARROS</h1>
{% comment %} <h2 class="text-white-50 mx-auto mt-2 mb-5">LISTADO DE CARROS</h2> {% endcomment %}
{% endblock h1_header %}


{% block contenido %}

<a style="color:white" class="navbar-brand" href={% url 'inicio:crear_carro' %}>Crear Carro</a><br> 

{% if object_list %}
    {% for carro in object_list %}
    <l1 class="text-white-50 mx-auto mt-2 mb-5">
        <a class="navbar-brand" href={% url 'inicio:mostrar_carro' carro.id %}>{{carro}}</a>
        <button>
            <a class="navbar-brand" href={% url 'inicio:modificar_carro' carro.id %}>Modificar</a> 
        </button>
        <button>
            <a class="navbar-brand" href={% url 'inicio:eliminar_carro' carro.id %}>Eliminar</a>  
        </button>
        <br> 
    </l1> 
    {% endfor %}

{% else %}

<p style="color: white">Aun no se han ingresado datos de carros por el momento.</p>

{% endif %}

{% endblock contenido %}


{% block about %}
{% endblock about %}

{% block contact%}
{% endblock contact%}

{% block footer %}
{% endblock footer %}

inicio/templates/inicio/modificar_carro.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Modificar Carro</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Modificar Carro</h1>
{% endblock h1_header %}


{% block contenido %}
<form style="color:white" action={% url 'inicio:modificar_carro' carro.id %} method="POST">
    {% csrf_token %}
    <table>
        {{form.media}}   
        {{form}}
    </table>
    <button>Modificar</button>
</form>
{% endblock contenido %}


{% block about %}
{% endblock about %}

{% block contact%}
{% endblock contact%}

{% block footer %}
{% endblock footer %}

inicio/templates/inicio/mostrar_carro.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Carros</title>
{% endblock title_head %}

{% block h1_header %}
<h1>{{carro}}</h1>
{% endblock h1_header %}


{% block contenido %}
<ul>
    <li>Modelo: {{carro.modelo}}</li>
    <li>Marca: {{carro.marca}}</li>
    <li>Descripcion: {{carro.descripcion | }}</li>
    <li>Precio: {{carro.precio}}</li>
    <li>Año de Fabricación: {{carro.anio_fabricacion}}</li>
</ul>
<p>
    <button>
        <a class="navbar-brand" href={% url 'inicio:modificar_carro' carro.id %}>Modificar</a>
    </button>
    <button>
        <a class="navbar-brand" href={% url 'inicio:eliminar_carro' carro.id %}>Eliminar</a>
    </button>
</p>
{% endblock contenido %}


{% block about %}
{% endblock about %}

{% block contact%}
{% endblock contact%}

{% block footer %}
{% endblock footer %}

templates/genericos/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>Holaaaa</title>
        {% endblock title_head %}
        
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'inicio/css/styles.css' %} rel="stylesheet" />
    </head>
    <body id="page-top">    
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container px-4 px-lg-5" >
                <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>
                <a class="navbar-brand" href={% url 'inicio:listar_carros' %}>Carros</a>
                <a class="navbar-brand" href={% url 'inicio:about' %}>About</a>
                
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        {% block l1_nav %}
                        
                        {% endblock l1_nav %}
                    </ul>
                </div>
                {% if request.user.is_authenticated %}
                {% if request.user.informacionextra.avatar %}
                <img src={{request.user.informacionextra.avatar.url}} alt="" height="40px">
                {% endif %}
                <a style="color:white" href={% url 'usuarios:editar_perfil' %}>{{request.user.username}}</a>
                <a class="btn btn-primary" href={% url 'usuarios:logout' %}>Cerrar Sesion</a>
                {% else %}
                <a class="btn btn-primary" href={% url 'usuarios:login' %}>Iniciar Sesion</a>
                <a class="btn btn-primary" href={% url 'usuarios:registro' %}>Registrarse</a>
                {% endif %}
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
                <div class="d-flex justify-content-center">
                    <div class="text-center">
                        {% block h1_header %}
                        <h1 class="mx-auto my-0 text-uppercase">Bienvenidos</h1>
                        <h2 class="text-white-50 mx-auto mt-2 mb-5">A free, responsive, one page Bootstrap theme created by Start Bootstrap.</h2>
                        {% endblock h1_header %}
                        
                        {% block contenido %}
                        {% endblock contenido %}
                        
                    </div>
                </div>
            </div>
        </header>
        
        <!-- Projects-->
        

        {% block contact %}
        <!-- Contact-->
        <section class="contact-section bg-black" id="contact"> 
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5">
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-map-marked-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Address</h4>
                                <hr class="my-4 mx-auto" />
                                <div class="small text-black-50">Huancayo, Junín, Perú</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-envelope text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Email</h4>
                                <hr class="my-4 mx-auto" />
                                <div class="small text-black-50"><a href="#!">rodriguez07renato@gmail.com</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-mobile-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Phone</h4>
                                <hr class="my-4 mx-auto" />
                                <div class="small text-black-50">+51 936487398</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="social d-flex justify-content-center">
                </div>
            </div>
        </section>
        {% endblock contact %}

        {% block footer %}
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50"><div class="container px-4 px-lg-5">Copyright &copy; Your Website 2023</div></footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static 'inicio/js/scripts.js' %}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        {% endblock footer %}
        
    </body>
</html>

usuarios/templates/usuarios/cambiar_contrasenia.html
{% extends 'genericos/base.html' %}

{% block title_head %}
                    <title>Cambio Contrasenia</title>
{% endblock title_head %}

{% block h1_header %}
                    <h1>Cambio Contrasenia</h1>
{% endblock h1_header %}


{% block contenido %}

{% if form.errors %}
<p style="color: #ec9898; font-size: 25px">Corrija los siguientes errores</p>
{% endif %}

<form style="color:white" action={% url 'usuarios:cambio_contrasenia' %} method="post">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button>Cambiar</button>
</form>
{% endblock contenido %}


{% block about %}
{% endblock about %}

{% block contact%}
{% endblock contact%}

{% block footer %}
{% endblock footer %}

usuarios/templates/usuarios/editar_perfil.html
{% extends 'genericos/base.html' %}

{% block title_head %}
                    <title>Editar Perfil</title>
{% endblock title_head %}

{% block h1_header %}
                    <h1>Editar Perfil</h1>
{% endblock h1_header %}

{% block contenido %}

{% if formulario.errors %}
<p style="color: #ec9898; font-size: 25px">Corrija los siguientes errores</p>
{% endif %}

<form style="color:white" action='' method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button type='button'><a class="navbar-brand" href={% url 'usuarios:cambio_contrasenia' %}>Cambiar contrasenia</a></button>
    <button>Guardar cambios</button>
</form>
{% endblock contenido %}


{% block about %}
{% endblock about %}

{% block contact%}
{% endblock contact%}

{% block footer %}
{% endblock footer %}

usuarios/templates/usuarios/login.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Inicio de Sesión</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Inicio de Sesión</h1>
{% endblock h1_header %}


{% block contenido %}
<form style="color:white" action={% url 'usuarios:login' %} method="post">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Iniciar Sesion</button>
</form>
{% endblock contenido %}


{% block about %}
{% endblock about %}

{% block contact%}
{% endblock contact%}

{% block footer %}
{% endblock footer %}

usuarios/templates/usuarios/logout.html
{% extends 'genericos/base.html' %}

{% block title_head %}
                    <title>Logout</title>
{% endblock title_head %}

{% block h1_header %}
                    <h1>Saliste de tu cuenta!!!</h1>
{% endblock h1_header %}

usuarios/templates/usuarios/registro.html
{% extends 'genericos/base.html' %}

{% block title_head %}
                    <title>Registro</title>
{% endblock title_head %}

{% block h1_header %}
                    <h1>Registrar una Cuenta</h1>
{% endblock h1_header %}

{% block contenido %}

{% if formulario.errors %}
<p style="color: #ec9898; font-size: 25px">Corrija los siguientes errores</p>
{% endif %}

<form style="color:white" action={% url 'usuarios:registro' %} method="post">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Registrarse</button>
</form>
{% endblock contenido %}


{% block about %}
{% endblock about %}

{% block contact%}
{% endblock contact%}

{% block footer %}
{% endblock footer %}